# 📁 Hands-On Sesi 7: File Handling & CSV

Selamat datang di sesi hands-on ke-8! Notebook ini adalah pendamping praktik dari materi slide **"File Handling & CSV"**.

**Tujuan belajar hari ini, kamu akan bisa:**
1. Membuka, membaca, dan menutup file dengan aman (`open()`, `close()`, `with open()`)
2. Menulis ke file dengan mode `"w"` (menimpa) dan `"a"` (menambah)
3. Memahami format CSV dan membacanya dengan `split()`
4. Mengenal dasar **Pandas** untuk mengolah data CSV
5. Menyelesaikan **Tugas Mandiri** di akhir notebook

> 💡 **Cara pakai notebook ini:** jalankan setiap cell dari atas ke bawah secara berurutan (klik cell, lalu tekan `Shift + Enter`). Beberapa cell akan membuat file contoh yang dipakai di cell-cell berikutnya, jadi jangan sampai ada yang terlewat!

## 🔧 Persiapan

Sebelum mulai, mari kita bersihkan dulu folder kerja kita dan siapkan tempat untuk menyimpan file-file latihan.

In [1]:
import os

# Membuat folder khusus untuk file-file latihan hari ini
os.makedirs("data_latihan", exist_ok=True)
print("Folder 'data_latihan' siap digunakan ✅")

Folder 'data_latihan' siap digunakan ✅

## 1️⃣ Kenapa Kita Butuh File Handling?

Coba perhatikan kode di bawah ini. Variabel `catatan` hanya hidup selama program berjalan di memori komputer.

Begitu program selesai dijalankan (atau Python di-*restart*), isi variabel itu **hilang total**. Ini seperti mengingat sesuatu hanya di kepala — gampang lupa!

File handling memungkinkan kita "menuliskan" data ke dalam file, seperti menulis di buku catatan, supaya datanya tetap ada meskipun program sudah selesai berjalan.

In [2]:
catatan = "Ini data penting yang hanya ada di memori"
print("Isi variabel saat ini:", catatan)

# Coba bayangkan: begitu notebook ini ditutup dan dibuka lagi,
# variabel 'catatan' di atas TIDAK akan ada lagi.
# Beda ceritanya kalau kita simpan ke FILE -> datanya tetap ada!

Isi variabel saat ini: Ini data penting yang hanya ada di memori

## 2️⃣ Membuka File di Python: Mode Akses

Setiap kali membuka file, kita perlu menentukan **mode**:

| Mode | Arti | Kegunaan |
|------|------|----------|
| `"r"` | *read* | Membuka file untuk **dibaca saja** |
| `"w"` | *write* | Membuka untuk **menulis** — isi lama akan **ditimpa** (hilang!) |
| `"a"` | *append* | Membuka untuk **menambah** data di baris paling akhir |

### Perintah `open()` dan pentingnya `close()`

Setiap kali kita `open()` sebuah file, kita **wajib** menutupnya kembali dengan `close()`. Kalau lupa, file bisa "terkunci" atau menyebabkan pemborosan memori.

In [3]:
# Membuka file dengan mode "r" untuk membaca -- tapi filenya belum pernah dibuat!
try:
    file = open("data_latihan/data.txt", "r")
    isi_awal = file.read()
    file.close()  # wajib! menutup pintu file
    print(isi_awal)
except FileNotFoundError as e:
    print("Error:", e)
    print("☝️ Ini kejadian karena file 'data.txt' belum pernah dibuat. Kita buat filenya di cell berikutnya.")

Halo, ini catatan pertamaku!

In [4]:
# Membuka file dengan mode "w" untuk menulis
file = open("data_latihan/data.txt", "w")
file.write("Halo, ini catatan pertamaku!")
file.close()  # wajib! menutup pintu file

print("File berhasil ditulis dan ditutup ✅")

File berhasil ditulis dan ditutup ✅

In [5]:
# Membuka file dengan mode "r" untuk membaca
file = open("data_latihan/data.txt", "r")
isi = file.read()
print(isi)
file.close()  # jangan lupa ditutup lagi!

Halo, ini catatan pertamaku!

## 3️⃣ Membaca File: `read()`, `readline()`, `readlines()`

Ada tiga cara umum untuk membaca isi file:

- **`read()`** → mengambil **seluruh isi** file sebagai satu teks panjang
- **`readline()`** → mengambil **satu baris saja**, dari atas ke bawah
- **`readlines()`** → mengambil **semua baris**, hasilnya berupa **list** of string

Mari kita coba satu per satu. Pertama, buat dulu file dengan beberapa baris.

In [6]:
with open("data_latihan/catatan_harian.txt", "w") as file:
    file.write("Bangun pagi\n")
    file.write("Belajar Python\n")
    file.write("Mengerjakan tugas\n")

print("File catatan_harian.txt berhasil dibuat ✅")

File catatan_harian.txt berhasil dibuat ✅

In [7]:
# --- read(): ambil semua isi sekaligus sebagai satu string ---
with open("data_latihan/catatan_harian.txt", "r") as file:
    isi = file.read()

print("Hasil read():")
print(isi)
print(type(isi))

Hasil read():
Bangun pagi
Belajar Python
Mengerjakan tugas

<class 'str'>

In [8]:
print(isi)

Bangun pagi
Belajar Python
Mengerjakan tugas

In [9]:
# --- readline(): ambil satu baris saja ---
with open("data_latihan/catatan_harian.txt", "r") as file:
    baris_pertama = file.readline()
    baris_kedua = file.readline()
    baris_ketiga = file.readline()

print("Baris pertama:", baris_pertama)
print("Baris kedua  :", baris_kedua)
print("Baris ketiga  :", baris_ketiga)

Baris pertama: Bangun pagi

Baris kedua  : Belajar Python

Baris ketiga  : Mengerjakan tugas

In [10]:
# --- readlines(): ambil semua baris jadi list ---
with open("data_latihan/catatan_harian.txt", "r") as file:
    semua_baris = file.readlines()

print("Hasil readlines():")
print(semua_baris)
print(type(semua_baris))

Hasil readlines():
['Bangun pagi\n', 'Belajar Python\n', 'Mengerjakan tugas\n']
<class 'list'>

In [11]:
semua_baris

['Bangun pagi\n', 'Belajar Python\n', 'Mengerjakan tugas\n']

## 4️⃣ ✅ Cara Aman: `with open()`

Perhatikan, di semua contoh di atas kita sudah pakai `with open(...) as file:`. Ini adalah **cara yang direkomendasikan** karena Python akan **otomatis menutup file** begitu blok `with` selesai — walaupun kita lupa memanggil `close()`.

Bandingkan dua cara berikut:

In [12]:
# Cara MANUAL (rawan lupa close())
file = open("data_latihan/data.txt", "r")
isi = file.read()
print(isi)
# file.close()
# 😬 kalau baris file.close() ini lupa ditulis, file tetap "terbuka"

Halo, ini catatan pertamaku!

In [13]:
type(file)

_io.TextIOWrapper

In [14]:
file.close()

In [15]:
# Cara AMAN dengan with open()
with open("data_latihan/data.txt", "r") as file:
    isi = file.read()
    print(isi)
# 🔒 begitu keluar dari blok 'with', file otomatis tertutup sendiri!

Halo, ini catatan pertamaku!

## 5️⃣ Menulis ke File: Mode `"w"` vs `"a"`

- Mode **`"w"`** akan **menimpa** seluruh isi file yang lama
- Mode **`"a"`** akan **menambahkan** baris baru di akhir, isi lama tetap aman

Mari kita buktikan perbedaannya.

In [16]:
# Mode "w" -> menimpa isi lama
with open("data_latihan/log.txt", "w") as file:
    file.write("Baris A")

with open("data_latihan/log.txt", "r") as file:
    print("Isi setelah mode w pertama kali:", file.read())

Isi setelah mode w pertama kali: Baris A

In [17]:
# Menulis LAGI dengan mode "w" -> isi lama HILANG, tertimpa total
with open("data_latihan/log.txt", "w") as file:
    file.write("Baris B")

with open("data_latihan/log.txt", "r") as file:
    print("Isi setelah mode w kedua kali:", file.read())
    print("⚠️  Perhatikan: 'Baris A' sudah hilang, tertimpa oleh 'Baris B'")

Isi setelah mode w kedua kali: Baris B
⚠️  Perhatikan: 'Baris A' sudah hilang, tertimpa oleh 'Baris B'

In [18]:
# Mode "a" -> menambah tanpa menghapus isi lama
with open("data_latihan/log.txt", "a") as file:
    file.write("\nBaris tambahan di akhir")

with open("data_latihan/log.txt", "r") as file:
    print("Isi setelah mode a:")
    print(file.read())
    print("✅ 'Baris B' masih ada, dan baris baru ditambahkan di bawahnya")

Isi setelah mode a:
Baris B
Baris tambahan di akhir
✅ 'Baris B' masih ada, dan baris baru ditambahkan di bawahnya

## 6️⃣ Apa itu CSV?

**CSV (Comma-Separated Values)** adalah cara menyimpan data tabel (seperti spreadsheet) dalam bentuk **teks murni**, di mana setiap kolom dipisahkan dengan tanda koma (`,`).

Contoh tabel:

| nama | usia | kota |
|------|------|------|
| Rani | 17 | Bandung |
| Budi | 16 | Jakarta |
| Sari | 17 | Surabaya |

Kalau ditulis dalam format CSV, jadinya seperti ini:

```
nama,usia,kota
Rani,17,Bandung
Budi,16,Jakarta
Sari,17,Surabaya
```

Baris pertama biasanya disebut **header** (nama kolom), dan baris-baris setelahnya adalah **data**.

Mari kita buat file CSV ini secara langsung dari Python.

In [19]:
with open("data_latihan/siswa.csv", "w") as file:
    file.write("nama,usia,kota\n")
    file.write("Rani,17,Bandung\n")
    file.write("Budi,16,Jakarta\n")
    file.write("Sari,17,Surabaya\n")

print("File siswa.csv berhasil dibuat ✅")

with open("data_latihan/siswa.csv", "r") as file:
    print(file.read())

File siswa.csv berhasil dibuat ✅
nama,usia,kota
Rani,17,Bandung
Budi,16,Jakarta
Sari,17,Surabaya

## 7️⃣ Membaca CSV dengan `split()`

Karena CSV hanyalah teks biasa dengan koma sebagai pemisah, kita bisa memecah setiap baris menjadi list menggunakan `split(",")`.

Alurnya:

```
"Rani,17,Bandung"  --split(",")-->  ["Rani", "17", "Bandung"]
```

> 💡 Kita juga memakai `.strip()` sebelum `.split()` untuk menghapus karakter enter (`\n`) di akhir baris.

In [20]:
with open("data_latihan/siswa.csv", "r") as file:
    header = file.readline()  # lewati baris pertama (header)
    print("Header:", header.strip())
    print("---")
    for baris in file:
        data = baris.strip().split(",")
        print(data)

Header: nama,usia,kota
---
['Rani', '17', 'Bandung']
['Budi', '16', 'Jakarta']
['Sari', '17', 'Surabaya']

In [21]:
# Mengambil kolom tertentu saja, misalnya hanya nama dan kota
with open("data_latihan/siswa.csv", "r") as file:
    file.readline()  # lewati header
    for baris in file:
        data = baris.strip().split(",")
        nama = data[0]
        usia = data[1]
        kota = data[2]
        print(f"{nama} usia {usia} tinggal di {kota}")

Rani usia 17 tinggal di Bandung
Budi usia 16 tinggal di Jakarta
Sari usia 17 tinggal di Surabaya

## 8️⃣ 🎯 Latihan Terpandu: Baca & Olah Data Nilai Siswa

Sekarang giliran kamu! Kita akan membaca file `nilai.csv` dan menampilkan nilai setiap siswa dengan format yang rapi, mirip dengan Live Build di kelas.

Jalankan cell di bawah untuk membuat file contohnya dulu.

In [22]:
with open("data_latihan/nilai.csv", "w") as file:
    file.write("nama,nilai\n")
    file.write("Rani,90\n")
    file.write("Budi,75\n")
    file.write("Sari,88\n")

print("File nilai.csv berhasil dibuat ✅")

File nilai.csv berhasil dibuat ✅

**Tugasmu:** lengkapi kode di bawah ini (bagian bertanda `# TODO`) supaya menghasilkan output seperti ini:

```
Rani -> nilai 90
Budi -> nilai 75
Sari -> nilai 88
```

Coba tebak dulu bagaimana caranya sebelum melihat kunci jawaban di cell sesudahnya!

In [23]:
with open("data_latihan/nilai.csv", "r") as file:
    header = file.readline()  # TODO: lewati baris header
    print("Header: ", header)
    for baris in file:
        data = baris.strip().split(",")   # TODO: pisahkan nama dan nilai
        nama = data[0]                     # TODO: ambil nama dari data
        nilai = data[1]                    # TODO: ambil nilai dari data
        print(f"{nama} -> nilai {nilai}")  # TODO: cetak dengan format rapi

Header:  nama,nilai

Rani -> nilai 90
Budi -> nilai 75
Sari -> nilai 88

<details>
<summary>👁️ Klik untuk melihat kunci jawaban</summary>

```python
with open("data_latihan/nilai.csv", "r") as file:
    header = file.readline()
    for baris in file:
        data = baris.strip().split(",")
        nama = data[0]
        nilai = data[1]
        print(f"{nama} -> nilai {nilai}")
```
</details>

## 9️⃣ ✨ Bonus: Intro to Pandas

Bagaimana kalau ada "Excel" langsung di dalam Python? Itulah **Pandas** — library populer untuk mengolah data tabel dengan sangat mudah.

Bandingkan: membaca CSV secara manual butuh beberapa baris `for` dan `split()`, sedangkan dengan Pandas cukup **satu baris kode**!

In [24]:
import pandas as pd

data = pd.read_csv("data_latihan/siswa.csv")
data

   nama  usia      kota
0  Rani    17   Bandung
1  Budi    16   Jakarta
2  Sari    17  Surabaya

In [25]:
data["usia"].mean()

np.float64(16.666666666666668)

In [26]:
siswa_df = pd.read_csv("data_latihan/siswa.csv")
siswa_df

   nama  usia      kota
0  Rani    17   Bandung
1  Budi    16   Jakarta
2  Sari    17  Surabaya

In [27]:
siswa_df.describe()

            usia
count   3.000000
mean   16.666667
std     0.577350
min    16.000000
25%    16.500000
50%    17.000000
75%    17.000000
max    17.000000

### Operasi Dasar Pandas

- `.head()` → melihat beberapa baris pertama
- `.describe()` → ringkasan statistik (rata-rata, min, max, dll)
- `data["kolom"]` → mengambil satu kolom saja
- `.mean()` → menghitung rata-rata

In [28]:
data_nilai = pd.read_csv("data_latihan/nilai.csv")

print("5 baris pertama:")
print(data_nilai.head())
print()
print("Ringkasan statistik:")
print(data_nilai.describe())

5 baris pertama:
   nama  nilai
0  Rani     90
1  Budi     75
2  Sari     88

Ringkasan statistik:
           nilai
count   3.000000
mean   84.333333
std     8.144528
min    75.000000
25%    81.500000
50%    88.000000
75%    89.000000
max    90.000000

In [29]:
# Mengambil kolom tertentu saja
print(data_nilai["nilai"])
print()

# Menghitung rata-rata nilai
rata_rata = data_nilai["nilai"].mean()
print("Rata-rata nilai kelas:", rata_rata)

0    90
1    75
2    88
Name: nilai, dtype: int64

Rata-rata nilai kelas: 84.33333333333333

In [30]:
# Filter: menampilkan siswa dengan nilai di atas 80
siswa_diatas_80 = data_nilai[data_nilai["nilai"] > 80 ]
siswa_diatas_80

   nama  nilai
0  Rani     90
2  Sari     88

In [31]:
# Filter: menampilkan siswa dengan nilai di atas 80 and data_nilai["nama"] == "Rani"
siswa_diatas_80 = data_nilai[(data_nilai["nilai"] > 80) & (data_nilai["nama"] == "Rani")]
siswa_diatas_80

   nama  nilai
0  Rani     90

In [32]:
# Filter: menampilkan siswa dengan nilai di atas 80 or data_nilai["nama"] == "Rani"
siswa_diatas_80 = data_nilai[(data_nilai["nilai"] > 80) | (data_nilai["nama"] == "Rani")]
siswa_diatas_80

   nama  nilai
0  Rani     90
2  Sari     88

In [33]:
data_nilai.to_json("data_latihan/nilai.json")

In [34]:
data_nilai_json = pd.read_json("data_latihan/nilai.json")
data_nilai_json

   nama  nilai
0  Rani     90
1  Budi     75
2  Sari     88

## 🎮 Latihan Cepat: Tebak Dulu, Baru Jalankan!

Sebelum menjalankan cell di bawah, coba **tebak dulu** apa outputnya. Tulis tebakanmu di kertas/kepala, baru jalankan untuk mengecek jawabanmu 😉

In [35]:
# Tebak dulu outputnya sebelum menjalankan cell ini!
with open("data_latihan/tebakan.txt", "w") as f:
    f.write("Halo")
with open("data_latihan/tebakan.txt", "w") as f:
    f.write("Dunia")
with open("data_latihan/tebakan.txt", "r") as f:
    print(f.read())

Dunia

In [36]:
# Tebak dulu outputnya sebelum menjalankan cell ini!
baris = "Andi,15,Yogyakarta"
data = baris.split(",")
print(len(data))
print(data[-1])

3
Yogyakarta

In [ ]:
housing_df = pd.read_csv("/content/sample_data/california_housing_train.csv")

housing_df

In [ ]:
housing_df.describe()

In [ ]:
housing_df.loc[(housing_df["housing_median_age"] < 5.0), "housing_median_age"] = 5.0

In [ ]:
housing_df[housing_df["housing_median_age"] < 5.0]

---

## 🧠 Tugas Mandiri

Sekarang saatnya berlatih sendiri! Kerjakan semua tugas di bawah ini di dalam cell kode yang sudah disediakan. Jangan lihat kunci jawaban dulu sebelum benar-benar mencoba ya 💪

### 📋 Tugas 1: Buku Catatan Pengeluaran

Buatlah program sederhana yang:
1. Membuat file `data_latihan/pengeluaran.txt`
2. Menuliskan **3 catatan pengeluaran** menggunakan mode `"w"` untuk baris pertama, lalu mode `"a"` untuk baris-baris berikutnya. Contoh isi:
   ```
   Beli buku - Rp 25000
   Beli pulsa - Rp 20000
   Jajan - Rp 15000
   ```
3. Membaca kembali file tersebut dan menampilkan seluruh isinya ke layar

In [41]:
# TUGAS 1 - Tulis kodemu di sini

# 1. Baris pertama pakai mode "w" (membuat file baru / menimpa)
with open("data_latihan/pengeluaran.txt", "w") as file:
    file.write("Beli buku - Rp 25000\n")

# 2. Baris-baris berikutnya pakai mode "a" (menambah, tidak menimpa)
with open("data_latihan/pengeluaran.txt", "a") as file:
    file.write("Beli pulsa - Rp 20000\n")

with open("data_latihan/pengeluaran.txt", "a") as file:
    file.write("Jajan - Rp 15000\n")

# 3. Membaca kembali & menampilkan seluruh isi file
with open("data_latihan/pengeluaran.txt", "r") as file:
    print("Isi pengeluaran.txt:")
    print(file.read())

Isi pengeluaran.txt:
Beli buku - Rp 25000
Beli pulsa - Rp 20000
Jajan - Rp 15000

### 📋 Tugas 2: Membuat & Membaca CSV Sendiri

Buatlah file CSV bernama `data_latihan/produk.csv` berisi data minimal 4 produk dengan kolom: `nama_produk`, `harga`, `stok`.

Lalu tulis program untuk:
1. Membaca file CSV tersebut baris per baris (**tanpa Pandas**, gunakan `split()`)
2. Menampilkan setiap produk dengan format: `Nama Produk - Rp Harga (Stok: X)`
3. Menghitung dan menampilkan **total nilai stok** (harga × stok) dari seluruh produk

In [42]:
# TUGAS 2 - Tulis kodemu di sini

# 1. Membuat file CSV produk.csv (4 produk, salah satunya stok tipis biar Tugas 4 kelihatan hasilnya)
with open("data_latihan/produk.csv", "w") as file:
    file.write("nama_produk,harga,stok\n")
    file.write("Buku Tulis,5000,50\n")
    file.write("Pulpen,3000,8\n")
    file.write("Penghapus,2000,30\n")
    file.write("Penggaris,4000,5\n")

# 2 & 3. Membaca CSV manual pakai split(), tampilkan tiap produk, & hitung total nilai stok
total_nilai_stok = 0

with open("data_latihan/produk.csv", "r") as file:
    header = file.readline()  # lewati baris header
    for baris in file:
        data = baris.strip().split(",")
        nama_produk = data[0]
        harga = int(data[1])
        stok = int(data[2])
        print(f"{nama_produk} - Rp {harga} (Stok: {stok})")
        total_nilai_stok += harga * stok

print("\nTotal nilai stok seluruh produk: Rp", total_nilai_stok)

Buku Tulis - Rp 5000 (Stok: 50)
Pulpen - Rp 3000 (Stok: 8)
Penghapus - Rp 2000 (Stok: 30)
Penggaris - Rp 4000 (Stok: 5)

Total nilai stok seluruh produk: Rp 354000

### 🐛 Tugas 3: Cari & Perbaiki Kesalahannya (Bug Hunting)

Kode di bawah ini punya **3 kesalahan** (mirip soal Mini Kuis di kelas!). Cari dan perbaiki ketiganya supaya kode bisa berjalan dan menghasilkan output yang benar.

Petunjuk: kesalahan terkait **mode file**, **delimiter**, dan **lupa menutup file**.

In [43]:
# Kode ini SENGAJA mengandung bug. Sudah diperbaiki di bawah ini:
# 1. Delimiter dibetulkan dari ";" -> "," (siswa.csv pakai koma)
# 2. Pakai with open(...) supaya file otomatis tertutup (tidak lupa close())
# 3. Mode "w" kedua diganti "a" supaya menambah baris, bukan menimpa file yang baru saja ditulis

with open("data_latihan/siswa.csv", "r") as file:
    header = file.readline()
    for baris in file:
        data = baris.strip().split(",")   # <- diperbaiki: delimiter koma
        print(data[0])
# tidak perlu file.close() manual -- with open() sudah menutupnya otomatis

with open("data_latihan/hasil_tugas3.txt", "w") as f:
    f.write("Selesai mengerjakan")
with open("data_latihan/hasil_tugas3.txt", "a") as f:   # <- diperbaiki: mode "a", bukan "w"
    f.write("\nSudah dicek ulang")

# Verifikasi hasil akhir
with open("data_latihan/hasil_tugas3.txt", "r") as f:
    print("\nIsi hasil_tugas3.txt:")
    print(f.read())

Rani
Budi
Sari

Isi hasil_tugas3.txt:
Selesai mengerjakan
Sudah dicek ulang

<details>
<summary>👁️ Klik untuk melihat petunjuk (jangan buka sebelum mencoba sendiri!)</summary>

1. Delimiter pada `siswa.csv` adalah koma `","`, bukan titik koma `";"`.
2. File yang dibuka dengan `open()` di baris pertama tidak pernah ditutup — tambahkan `file.close()`, atau lebih baik ganti seluruhnya memakai `with open(...)`.
3. Baris terakhir memakai mode `"w"` lagi, padahal tujuannya menambah baris baru — seharusnya memakai mode `"a"`.
</details>

### ✨ Tugas 4 (Bonus): Olah Data dengan Pandas

Menggunakan file `data_latihan/produk.csv` yang kamu buat di Tugas 2:

1. Baca file tersebut menggunakan `pd.read_csv()`
2. Tampilkan `.head()` dan `.describe()` dari data tersebut
3. Tampilkan hanya produk dengan `stok` kurang dari 10 (produk yang perlu di-restock)
4. Hitung rata-rata harga seluruh produk menggunakan `.mean()`

In [44]:
# TUGAS 4 (BONUS) - Tulis kodemu di sini
import pandas as pd

produk_df = pd.read_csv("data_latihan/produk.csv")

print("5 baris pertama:")
print(produk_df.head())

print("\nRingkasan statistik:")
print(produk_df.describe())

print("\nProduk yang perlu di-restock (stok < 10):")
print(produk_df[produk_df["stok"] < 10])

print("\nRata-rata harga seluruh produk:", produk_df["harga"].mean())

5 baris pertama:
  nama_produk  harga  stok
0  Buku Tulis   5000    50
1      Pulpen   3000     8
2   Penghapus   2000    30
3   Penggaris   4000     5

Ringkasan statistik:
             harga       stok
count     4.000000   4.000000
mean   3500.000000  23.250000
std    1290.994449  21.029741
min    2000.000000   5.000000
25%    2750.000000   7.250000
50%    3500.000000  19.000000
75%    4250.000000  35.000000
max    5000.000000  50.000000

Produk yang perlu di-restock (stok < 10):
  nama_produk  harga  stok
1      Pulpen   3000     8
3   Penggaris   4000     5

Rata-rata harga seluruh produk: 3500.0

---

## ✅ Ceklis Penilaian Mandiri

Sebelum mengumpulkan, cek kembali pekerjaanmu:

- [ ] Tugas 1: file berhasil dibuat, ditulis dengan mode `"w"` & `"a"`, lalu dibaca ulang
- [ ] Tugas 2: CSV berhasil dibuat dan dibaca manual dengan `split()`, total nilai stok muncul
- [ ] Tugas 3: ketiga bug berhasil ditemukan dan diperbaiki, kode berjalan tanpa error
- [ ] Tugas 4 (bonus): berhasil memakai Pandas untuk membaca & memfilter data

## 🎉 Penutup

Kerja bagus sudah menyelesaikan hands-on Sesi 8! Kemampuan file handling dan CSV ini akan sangat sering dipakai saat kamu mulai bekerja dengan data nyata di dunia kerja maupun proyek pribadi.

Sampai jumpa di **Sesi 9**! 🚀